<?php
// R7: Estado de Trámites por Nave
$filters = ['fecha_desde' => $_GET['fecha_desde'] ?? date('Y-m-01'), 'fecha_hasta' => $_GET['fecha_hasta'] ?? date('Y-m-d')];
$stmt = $pdo->prepare("SELECT t.*, v.name as vessel_name, vc.viaje_id, e.name as entidad_name, EXTRACT(EPOCH FROM (t.fecha_fin - t.fecha_inicio))/3600 as lead_time_h FROM aduanas.tramite t JOIN portuario.vessel_call vc ON t.vessel_call_id = vc.id JOIN portuario.vessel v ON vc.vessel_id = v.id JOIN aduanas.entidad e ON t.entidad_id = e.id WHERE t.fecha_inicio >= :fecha_desde AND t.fecha_inicio <= :fecha_hasta ORDER BY t.fecha_inicio DESC");
$stmt->execute($filters);
$data = $stmt->fetchAll(PDO::FETCH_ASSOC);
$total = count($data);
$aprobados = count(array_filter($data, fn($r) => $r['estado'] == 'APROBADO'));
$pendientes = count(array_filter($data, fn($r) => in_array($r['estado'], ['INICIADO','EN_REVISION','OBSERVADO'])));
include 'layout/header.php';
?>
<div class="page-header"><h1>📦 R7: Estado de Trámites por Nave</h1><p>Trámites completos pre-arribo, lead time</p></div>
<div class="card" style="margin-bottom: 2rem;"><div class="card-body"><form method="GET" style="display: flex; gap: 1rem; align-items: end; flex-wrap: wrap;"><input type="hidden" name="page" value="report-r7"><div><label>Fecha Desde:</label><input type="date" name="fecha_desde" value="<?=htmlspecialchars($filters['fecha_desde'])?>" class="form-input"></div><div><label>Fecha Hasta:</label><input type="date" name="fecha_hasta" value="<?=htmlspecialchars($filters['fecha_hasta'])?>" class="form-input"></div><button type="submit" class="btn btn-primary">🔍 Filtrar</button></form></div></div>
<div class="stats-grid" style="margin-bottom: 2rem;"><div class="stat-card blue"><div class="stat-content"><div class="stat-number"><?=$total?></div><div class="stat-label">Total Trámites</div></div></div><div class="stat-card green"><div class="stat-content"><div class="stat-number"><?=$aprobados?></div><div class="stat-label">Aprobados</div></div></div><div class="stat-card orange"><div class="stat-content"><div class="stat-number"><?=$pendientes?></div><div class="stat-label">Pendientes</div></div></div><div class="stat-card purple"><div class="stat-content"><div class="stat-number"><?=$total > 0 ? round(($aprobados/$total)*100, 2) : 0?>%</div><div class="stat-label">% Completitud</div></div></div></div>
<div class="card"><div class="card-header"><h3>📊 Trámites por Nave</h3></div><div class="card-body"><table class="data-table"><thead><tr><th>Trámite ID</th><th>Nave</th><th>Viaje</th><th>Régimen</th><th>Entidad</th><th>Estado</th><th>Lead Time (h)</th></tr></thead><tbody><?php if (empty($data)): ?><tr><td colspan="7" style="text-align: center; color: #666;">No hay datos disponibles</td></tr><?php else: ?><?php foreach ($data as $row): ?><?php $badge = $row['estado']=='APROBADO'?'badge-success':($row['estado']=='RECHAZADO'?'badge-danger':'badge-warning'); ?><tr><td><?=htmlspecialchars($row['tramite_ext_id'])?></td><td><?=htmlspecialchars($row['vessel_name'])?></td><td><?=htmlspecialchars($row['viaje_id'])?></td><td><?=htmlspecialchars($row['regimen'])?></td><td><?=htmlspecialchars($row['entidad_name'])?></td><td><span class="badge <?=$badge?>"><?=htmlspecialchars($row['estado'])?></span></td><td><?=$row['lead_time_h'] ? round($row['lead_time_h'], 2) : 'N/A'?></td></tr><?php endforeach; ?><?php endif; ?></tbody></table></div></div>
<?php include 'layout/footer.php'; ?>
