<?php
// R5: Cumplimiento de Citas
$filters = ['fecha_desde' => $_GET['fecha_desde'] ?? date('Y-m-01'), 'fecha_hasta' => $_GET['fecha_hasta'] ?? date('Y-m-d')];
$stmt = $pdo->prepare("SELECT a.*, t.placa, c.name as company_name, EXTRACT(EPOCH FROM (a.hora_llegada - a.hora_programada))/60 as desvio_min FROM terrestre.appointment a JOIN terrestre.truck t ON a.truck_id = t.id JOIN terrestre.company c ON a.company_id = c.id WHERE a.hora_programada >= :fecha_desde AND a.hora_programada <= :fecha_hasta ORDER BY a.hora_programada DESC");
$stmt->execute($filters);
$data = $stmt->fetchAll(PDO::FETCH_ASSOC);
$total = count($data);
$no_show = count(array_filter($data, fn($r) => $r['estado'] == 'NO_SHOW' || !$r['hora_llegada']));
$tarde = count(array_filter($data, fn($r) => $r['hora_llegada'] && abs($r['desvio_min']) > 15));
$a_tiempo = $total - $no_show - $tarde;
include 'layout/header.php';
?>
<div class="page-header"><h1>✅ R5: Cumplimiento de Citas</h1><p>Clasificación: A tiempo, Tarde, No Show</p></div>
<div class="card" style="margin-bottom: 2rem;"><div class="card-body"><form method="GET" style="display: flex; gap: 1rem; align-items: end; flex-wrap: wrap;"><input type="hidden" name="page" value="report-r5"><div><label>Fecha Desde:</label><input type="date" name="fecha_desde" value="<?=htmlspecialchars($filters['fecha_desde'])?>" class="form-input"></div><div><label>Fecha Hasta:</label><input type="date" name="fecha_hasta" value="<?=htmlspecialchars($filters['fecha_hasta'])?>" class="form-input"></div><button type="submit" class="btn btn-primary">🔍 Filtrar</button></form></div></div>
<div class="stats-grid" style="margin-bottom: 2rem;"><div class="stat-card green"><div class="stat-content"><div class="stat-number"><?=$total > 0 ? round(($a_tiempo/$total)*100, 2) : 0?>%</div><div class="stat-label">A Tiempo</div></div></div><div class="stat-card orange"><div class="stat-content"><div class="stat-number"><?=$total > 0 ? round(($tarde/$total)*100, 2) : 0?>%</div><div class="stat-label">Tarde</div></div></div><div class="stat-card red"><div class="stat-content"><div class="stat-number"><?=$total > 0 ? round(($no_show/$total)*100, 2) : 0?>%</div><div class="stat-label">No Show</div></div></div><div class="stat-card blue"><div class="stat-content"><div class="stat-number"><?=$total?></div><div class="stat-label">Total Citas</div></div></div></div>
<div class="card"><div class="card-header"><h3>📊 Detalle de Citas</h3></div><div class="card-body"><table class="data-table"><thead><tr><th>Placa</th><th>Empresa</th><th>Hora Programada</th><th>Hora Llegada</th><th>Desvío (min)</th><th>Clasificación</th></tr></thead><tbody><?php if (empty($data)): ?><tr><td colspan="6" style="text-align: center; color: #666;">No hay datos disponibles</td></tr><?php else: ?><?php foreach ($data as $row): ?><?php $clasificacion = !$row['hora_llegada'] ? 'NO_SHOW' : (abs($row['desvio_min']) <= 15 ? 'A_TIEMPO' : 'TARDE'); $badge = $clasificacion == 'A_TIEMPO' ? 'badge-success' : ($clasificacion == 'TARDE' ? 'badge-warning' : 'badge-danger'); ?><tr><td><?=htmlspecialchars($row['placa'])?></td><td><?=htmlspecialchars($row['company_name'])?></td><td><?=date('d/m/Y H:i', strtotime($row['hora_programada']))?></td><td><?=$row['hora_llegada'] ? date('d/m/Y H:i', strtotime($row['hora_llegada'])) : 'N/A'?></td><td><?=$row['hora_llegada'] ? round($row['desvio_min'], 2) : 'N/A'?></td><td><span class="badge <?=$badge?>"><?=$clasificacion?></span></td></tr><?php endforeach; ?><?php endif; ?></tbody></table></div></div>
<?php include 'layout/footer.php'; ?>
